echo "# terraform-cicd" >> README.md
git init
git add README.md
git commit -m "Initial Commit"
git branch -M main
git remote add origin https://github.com/alickgoh/terraform-cicd.git
git push -u origin main
